### PR TITLE
Implement unit tests

### PR DESCRIPTION
**Pull request by laerlingSAP**
- [x] Remove taskflow tests and `test_f5_driver`, since those are old and mostly obsolete.
- [x] Check whether we can derive an Octavia driver test class and turn generic tests on/off
- [ ] Test AS3 generating code as-is
  - [ ] Check whether `as3classes.BaseDescription.to_dict` is needed outside of testing or can be replaced by `as3classes.BaseDescription.to_json` at least in the tests.
  - [ ] Check code paths using `as3classes.required` function
- [ ] Test AS3 generating code as-used
- [ ] Implement missing test parts for functionality that should exist but does not yet.
- [ ] make TravisCI pipeline (testing python2 and python3, see e.&nbsp;g. tox.ini in octavia-lib)

### CODE REVIEW

**Comment by laerlingSAP** [comment]
There are some driver and agent tests in `octavia/tests/unit/amphorae`, but they don't seem to be generic enough to be reusable for the f5 driver and agent.

**Comment by laerlingSAP** [comment]
As @notandy and I discussed in our last phone call: This PR will be merged and then be dropped for the time being, in favor of regression tests (#30).

**Comment by notandy** [comment]
Could you rebase on master to get rid of the master -> unittest merges?

**Comment by laerlingSAP** [comment]
I don't think rebasing is a good idea because in some commits prior to merges there is code that tests functionality which was removed in `master` (and thus with the merge in `unittests` as well). It is better to retain that code, in case said functionality be introduced again.
Rebasing would mean to either have intermediate commits which break tests (because the test code does not match the SUT code from `master`) or to throw said test code away while rebasing. A beautiful commit tree is not worth such compromises in my book.

**Pull request merged**
