### PR TITLE
Fix: AS3 unchecked mode called 'unsafe' instead of 'unchecked'

### PR DESCRIPTION
**Pull request by BenjaminLudwigSAP**
Merging and deploying next week.
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3.36/userguide/unchecked-mode.html

### CODE REVIEW

**Comment by m-kratochvil** [comment]
Just an FYI, I found an email from F5 (Daniel Stokes - AS3 dev team) from 2019 where `unsafe=true` query param is used. Then I found another email from F5 (support case related) from 2021 where they already use `unchecked=true` query param.
There must have been a point between 2019 and 2021 where F5 renamed the mode from `unsafe` to `unchecked`. But I failed to find any trace of it online.

**Review by m-kratochvil — APPROVED** [review]
lgtm

**Comment by BenjaminLudwigSAP** [comment]
It is unclear to me why we closed this PR. Even though unchecked mode was only temporary needed for one device, the naming should still be correct. So I'm reopening this.

**Review by m-kratochvil — APPROVED** [review]
Also don't know why this was closed, it is needed.

**Pull request merged**
